### ISSUE TITLE
d3.medianIndex / d3.quantileIndex?

### ISSUE THREAD

**Issue by EE2dev** [d3/d3-array#140]
I suggest to also have a function d3.medianIndex(). E.g. it could return an array 

- with one element: the index of the corresponding element - in case the array.length is uneven
- with two elements: the indices of the elements from which the mean was taken - in case the array.length is even

**Comment by Fil** [comment]
Related: #138; in both cases we're trying to get better access to the value we've located in the array.

**Comment by Fil** [comment]
I've tried to implement d3.quantileIndex in https://observablehq.com/d/c6c8a233930664d8 ;  in order to keep track of the indices, we need to create an array of indices, then call quickselect on that array with a comparator that looks up the values in the original array. It's a quite bit more difficult to track, and implies the reservation of more memory.

Another option is to seek the indices after determining the quantile, by running through the values to find the closest inferior and closest superior values (see the "Alternative" part of the notebook). This approach is leaner, and the added time is negligible.

In terms of API I'd rather always return an array of two indices—which may be identical for odd lengths.

Of course `d3.medianIndex(values, valueof)` would be `d3.quantileIndex(values, 0.5, valueof)`

**Comment by EE2dev** [comment]
Thanks Fil! Looks great to me, also agree on your suggestion for the cleaner API.
