### ISSUE TITLE
d3.summarize (for box plots)?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-array#180]
Something like:

```js
function summarize(iterable, value = identity) {
  const values = map(iterable, value).sort(ascending);
  const min = values[0];
  const max = values[values.length - 1];
  const q1 = quantileSorted(values, 0.25);
  const q2 = quantileSorted(values, 0.50);
  const q3 = quantileSorted(values, 0.75);
  const iqr = q3 - q1; // interquartile range
  const r0 = Math.max(min, q1 - iqr * 1.5);
  const r1 = Math.min(max, q3 + iqr * 1.5);
  return {
    quartiles: [q1, q2, q3],
    range: [r0, r1],
    outliers: values.filter(v => v < r0 || v > r1)
  };
}
```

Although probably outliers should be a subset of the input elements rather than the mapped values?

**Comment by curran** [comment]
Whoah great idea!

**Comment by curran** [comment]
Possible to split into `summarize` and `summarizeSorted`, to skip the sort step in case values are already sorted.

**Comment by mbostock** [comment]
I’ll probably use quantile instead of quantileSorted to avoid the sort step.

**Comment by curran** [comment]
Years ago I implemented this box plot summary in much the same way, and it failed QA in that company because the output did not match the output from R, which the company viewed as the "industry standard".

Just wanted to flag that it may be worth doing a comparison of the output between this and the same summary function in R. The discrepancies came up with a small number of values as input, and degenerate cases as far as I recall.

**Comment by akngs** [comment]
If `r0` and `r1` are for whiskers, and if we are trying to implement box plots according to John Tukey's "schematic plot," they should be calculated differently. The correct way to calculate whiskers, according to p44-47 of Exploratory Data Analysis, are:

> **the smallest data within** `Q1 - 1.5 IQR` and **the largest data within** `Q3 + 1.5 IQR`

This means that the whiskers should always indicate actual data points. For example, given dataset `[0, 3, 4.4, 4.5, 4.6, 5, 7]`, the following shows incorrectly rendered whiskers:

![image](https://user-images.githubusercontent.com/2233956/120169931-66e3db80-c23b-11eb-8d61-20190c63f07e.png)

The following shows the correct way:

![image](https://user-images.githubusercontent.com/2233956/120169988-782ce800-c23b-11eb-8bec-66ba8e09b249.png)

Vegalite also has the same problem but they've fixed it since [v3.0.0-rc13](https://github.com/vega/vega-lite/releases/tag/v3.0.0-rc13).

Here's a detailed explanation with a demo: https://observablehq.com/@akngs/vega-lite-renders-box-plots-differently

**Comment by Fil** [comment]
Agree with @akngs — on this issue see also https://github.com/observablehq/plot/issues/13#issuecomment-747955182

**Comment by Fil** [comment]
does the following look correct & efficient? It is robust against null, undefined and NaN, and seems to do the right thing (including for an empty data array, where it returns undefined quartiles and whiskers)

~~~js
function summarize(iterable, value = identity) {
  const values = map(iterable, value)
    .filter((d) => d != null && d >= d)
    .sort(ascending);
  const min = values[0];
  const max = values[values.length - 1];
  const q1 = quantileSorted(values, 0.25);
  const q2 = quantileSorted(values, 0.5);
  const q3 = quantileSorted(values, 0.75);
  const iqr = q3 - q1; // interquartile range
  const w0 = Math.max(min, q1 - iqr * 1.5);
  const w1 = Math.min(max, q3 + iqr * 1.5);
  let i = -1;
  while (values[++i] < w0);
  const r0 = values[i];
  while (values[++i] <= w1);
  const r1 = values[i - 1];
  return {
    quartiles: [q1, q2, q3],
    range: [r0, r1],
    outliers: values.filter((v) => v < r0 || v > r1)
  };
}
~~~

https://observablehq.com/@fil/whiskers-180

**Comment by mbostock** [comment]
I have corrected the implementation here: https://observablehq.com/@mbostock/plot-box

**Comment by akngs** [comment]
Looks good to me :)

**Comment by mbostock** [comment]
We’ve implemented a nice box mark in Plot, so I’m not planning on implementing a separate summary method in d3-array. https://github.com/observablehq/plot/blob/main/README.md#box
