### ISSUE TITLE
ticks is not inclusive?

### ISSUE THREAD

**Issue by fasiha** [d3/d3-array#30]
When asking for 4-ish points between 0 and 24, I expected to get 0, 5, 10, 15, 20, 25, but `ticks` stops at 20:
```js
var a = require('d3-array')
// undefined
a.ticks(0, 24, 4)
// [ 0, 5, 10, 15, 20 ]
```
I believe this is because when [calculating the range's stopping point](https://github.com/d3/d3-array/blob/d0c16be6d42bb50556a8670af440d3dcc404ba56/src/ticks.js#L11), you use `floor(24/step) * step + step/2` which in this case is 22.5, and won't include 24.

Replacing that `floor` with `ceil` does the trick in this case, but breaks a couple of your tests… I'll continue poking it and see if I can work out the correct logic.

**Comment by fasiha** [comment]
Assuming I'm not being dyslexic and the first/last elements of `tick`'s output should bracket start/stop, what you're trying to achieve is the `range`'s start and stop to be the multiple of `step` that is rounded _away_ from 0 (to +/- infinity). This does that:
```js
function roundAwayFromZero(x) { return Math.ceil(Math.abs(x)) * Math.sign(x); }

export default function(start, stop, count) {
  var step = tickStep(start, stop, count);
  return range(
    roundAwayFromZero(start / step) * step,
    roundAwayFromZero(stop / step) * step + step / 2, // inclusive
    step
  );
}
```
This ensures that both the first and last elements of the result are inclusive.

(This is important because the first element fails to be inclusive in a slightly modified example: with current code, `ticks(1,24,4) // => [ 5, 10, 15, 20 ]`—no 1 nor 24.)

This breaks _one_ test: `ticks(-10, 10, 1)`, with a `step` size of 20, will have to be `[-20, -0, 20]`, because of round-away-from-zero behavior. If this is acceptable to you (i.e., if you agree to guarantee inclusivity even for `count` = 1), I can send over a PR with the above.

**Comment by fasiha** [comment]
(Sorry my last post was completely non-sensical, so I deleted it and started again. Sorry for the barrage of emails this issue has created for you!)

I think you just switched `floor` and `ceil` there, in `ticks`: you want the start of the range to be (after dividing by `step`) rounded to -infinity, and the end of the range to be rounded to +infinity. With this in place, the usual requirements of inclusivity are met: `ticks(1, 24, 4)` goes from 0 to 25 in steps of 5 (with the previous code, it would go from 5 to 20 in steps of 5).

The only problem with this is that it breaks one test: `ticks(-10, 10, 1)`, in order to be inclusive, has to be `[-20, -0, 20]`. If this is ok, i.e., if `count` = 1 still requires inclusivity, then I can make a PR with the above fix, plus an adjusted test.

**Comment by mbostock** [comment]
> the first/last elements of tick's output should bracket start/stop

That’s not what I meant by *inclusive*. Ticks are inclusive in the sense that they may include the specified *start* and *stop* values if (and only if) they are exact, nicely-rounded values consistent with the determined tick step. More formally, each returned tick *t* satisfies *start* ≤ *t* and *t* ≤ *stop*. (If they were exclusive, then the relationship would instead be *start* < *t* and *t* < *stop*.)

Your *stop* of 24 is greater than the next tick 25, so 25 is not included.

```js
d3.ticks(0, 24, 4); // [0, 5, 10, 15, 20]
```

If you increase the bounds to [0, 25] you’ll see that it will include the upper bound exactly, thereby demonstrating that it is indeed inclusive:

```js
d3.ticks(0, 25, 4); // [0, 5, 10, 15, 20, 25]
```

As you mentioned, yes, internally, the upper bound is calculated as follows:

```js
Math.floor(stop / step) * step + step / 2
```

Since the *step* is the result of d3.tickStep (here 5) that works out to:

```js
Math.floor(24 / 5) * 5 + 5 / 2 // 22.5
```

This is less than the *stop* of 24, but 24 is not a multiple of the *step*, so it’s still correct. If the *stop* were a multiple of *step*—say if *step* were instead 4—then it would be greater than *stop*:

```js
Math.floor(24 / 4) * 4 + 4 / 2 // 26
```

In other words, the greatest tick is ⌊*stop* / *step*⌋ × *step* (⌊24 / 5⌋ × 5 = 20). The only reason for the additional *step* / 2 is that [d3.range](https://github.com/d3/d3-array#range), which is used internally by d3.ticks, treats *stop* as exclusive, unlike d3.ticks. I could have used an epsilon value instead, such as this:

```js
Math.floor(stop / step) * step + 1e-6
```

But d3.ticks is intended to work for arbitrary values, so *step* can be arbitrarily small and it’s better to use something appropriate to the value of *step*.

If you want the ticks to surround *start* and *stop*, then you need the equivalent of [*continuous*.nice](https://github.com/d3/d3-scale#continuous_nice) from [d3-scale](https://github.com/d3/d3-scale). See [linear.js](https://github.com/d3/d3-scale/blob/master/src/linear.js) for the implementation. It’s a little tricky since you need to call d3.tickStep twice, since increasing the extent (lowing the *start* and raising the *stop*) can also change the inferred *step*. But you can skip that step if you want different behavior:

```js
var start = 0, stop = 24, count = 4;
var step = d3.tickStep(start, stop, count);
var ticks = d3.range(Math.floor(start / step) * step, Math.ceil(stop / step) * step + step / 2, step);
```

**Comment by fasiha** [comment]
Doh, many thanks for taking this much time to explain—your first paragraph, defining "inclusive" would have sufficed!
