### ISSUE TITLE
why create `number.js` instead of using `Number()`? 

### ISSUE THREAD

**Issue by EmbraceLife** [d3/d3-array#36]
Hi Mike, 
I found myself choosing an approach to learn d3 by understanding its source code. I start with the functions in `d3-array`, so far it goes smooth. 

I noticed `number.js` is used to create `mean.js`, but not included as `d3.number`. I read the code and it seems `Number()` can do the same. So, I wonder what is the necessity of writing `number.js` here. 

Thanks

**Comment by mbostock** [comment]
The definition of 'number', which is used to coerce a value to a number, is slightly different than Number(x) (or the equivalent and faster +x): it treats the null value as NaN rather than zero. I do this because null is often used to represent missing data (interchangeably with undefined), and coercing it to NaN is therefore safer than silently replacing it with the defined value zero. The other methods in this library ignore NaN values post-coercion.

This function isn’t exported because it is only intended to be used privately by this library. In general, my default stance is to keep things private to keep the API smaller, to reduce the amount of documentation and support I need to provide, and other benefits.

**Comment by mbostock** [comment]
The definition of 'number', which is used to coerce a value to a number, is
slightly different than Number(x) (or the equivalent and faster +x): it
treats the null value as NaN rather than zero. I do this because null is
often used to represent missing data (interchangeably with undefined), and
coercing it to NaN is therefore safer than silently replacing it with the
defined value zero. The other methods in this library ignore NaN values
post-coercion.

This function isn’t exported because it is only intended to be used
privately by this library. In general, my default stance is to keep things
private to keep the API smaller, to reduce the amount of documentation and
support I need to provide, and other benefits.

**Comment by EmbraceLife** [comment]
Thanks, this is very helpful.
