### ISSUE TITLE
why create `array.js` given `array.map` and `array.slice` are available?

### ISSUE THREAD

**Issue by EmbraceLife** [d3/d3-array#37]
My speculation on the reason why creating [`array.js`](https://github.com/d3/d3-array/blob/master/src/array.js) given `array.map` and `array.slice` are available, is to use the code like the following found in [`histogram.js`](https://github.com/d3/d3-array/blob/master/src/histogram.js)

`slice.call(_)`

Is it because `array.slice` could not run as `slice.call(_)`?  If so, what does this `.call` do exactly for `slice`? Where can I learn more about this kind of usage?

Thanks

**Comment by mbostock** [comment]
The reason is that sometimes array-like objects are passed, such as arguments. These objects do not implement array methods such as *array*.slice, but are otherwise like arrays. Also, if you were being paranoid, someone could override *array*.slice to change the behavior so that it did not return a defensive copy. So it’s safer to rely on the built-in method.
