### ISSUE TITLE
How to create histogram with fixed bin width

### ISSUE THREAD

**Issue by netzwerg** [d3/d3-array#46]
I am trying to create a histogram with a specific number of bins which should all have the same width (i.e. the domain should be uniformly divided):

I started by using `x.ticks()` (Option 1):

```javascript
const binCount = 5;
const data = [1, 2, 3, 4, 4.7];
const [min, max] = d3.extent(data);
const x = d3.scaleLinear().domain([min, max]);

// Option 1: Tick-based thresholds

const histogram1 = d3.histogram()
  .domain(x.domain())
  .thresholds(x.ticks(binCount));
const bins1 = histogram1(data);

console.log("Option 1 bin widths: " + bins1.map(b => (b.x1 - b.x0)));
// 1,1,1,0.7000000000000002
```
The last bin is narrower than all other bins (to be expected based on how `ticks` works).

For `histogram.thresholds([count])`, the docs state that:

> If a count is specified instead of an array of thresholds, then the domain will be uniformly divided into approximately count bins

This is not what I observe (Option 2):

```javascript
// Option 2: Count-based thresholds

const histogram2 = d3.histogram()
  .domain(x.domain())
  .thresholds(binCount);

const bins2 = histogram2(data);

console.log("Option 2 bin widths: " + bins2.map(b => (b.x1 - b.x0)));
// 1,1,1,0.7000000000000002
```

**Q: What's the proper invocation of `histogram.thresholds([count])`?**

I currently use a manual array of thresholds (Option 3):

```javascript
// Option 3: Range-based thresholds

const thresholds = d3.range(min, max, (max - min) / binCount);
const histogram3 = d3.histogram()
  .domain(x.domain())
  .thresholds(thresholds);

const bins3 = histogram3(data);

console.log("Option 3 bin widths: " + bins3.map(b => (b.x1 - b.x0)));
// 0.74,0.74,0.7399999999999998,0.7400000000000002,0.7400000000000002
```

This works, but seems overly complex for such a simple use case...

**Comment by mbostock** [comment]
Regarding the first or last bin not being the same width as the others: that is because given *n* thresholds, *n* + 1 bins will be produced. The first bin (`bins[0]`) contains any value less than the first threshold (`thresholds[0]`); the last bin (`bins[thresholds.length]`) contains any value greater than or equal to the last threshold (`thresholds[thresholds.length - 1]`). 

If you prefer, you can consider the effective width of the first and last bin as infinite, since they are bounded only by the input *data* and not the *thresholds*. The `bins[0].x0` is equal to `domain[0]` and `bins[thresholds.length].x1` is equal to `domain[1]` given the histogram’s [domain](https://github.com/d3/d3-array/blob/master/README.md#histogram_domain) which defaults to the [extent](https://github.com/d3/d3-array/blob/master/README.md#extent) of the input *data*.

If you want to force the domain to coincide exactly with the tick interval, you can use [d3.range](https://github.com/d3/d3-array/blob/master/README.md#range) to manually create the ticks as you discuss in option 3. If you also want the tick thresholds to be “human-readable” (per the design of [d3.ticks](https://github.com/d3/d3-array/blob/master/README.md#ticks)) you can [nice your domain](https://github.com/d3/d3-scale/blob/master/README.md#continuous_nice) before computing the ticks, and then use [*scale*.ticks](https://github.com/d3/d3-scale/blob/master/README.md#continuous_ticks):

```js
var data = [1, 2, 3, 4, 4.7];
var x = d3.scaleLinear().domain(d3.extent(data)).nice();
var histogram = d3.histogram().domain(x.domain()).thresholds(x.ticks(5));
var bins = histogram(data);
console.log("bin widths: " + bins.map(b => b.x1 - b.x0));
```

You could also use [d3.tickStep](https://github.com/d3/d3-array/blob/master/README.md#tickStep) to nice your histogram’s domain manually, but that’s exactly what [*linear*.nice](https://github.com/d3/d3-scale/blob/master/src/linear.js#L18) does.

**Comment by netzwerg** [comment]
Thank you for the detailed answer – I wish you a happy new year 🎉 🍾 🎆
