### ISSUE TITLE
Extent of extents

### ISSUE THREAD

**Issue by AmatanHead** [d3/d3-array#64]
Hello!

When working with multiple series of data, it's a common task to calculate extent of extents, and currently I see no clear way of doing this.

I propose to change `d3.extent`, `d3.min`, etc. to treat arrays differently (e.g. flatten a passed array) so that code like

```
d3.extent(data, d => d3.extent(d))
```

yields a single pair of values.

Or maybe, if changing `d3.extent`&Cº seems confusing, it might be good add a second accessor parameter to the `d3.merge` so that it looks like

```
d3.extent(d3.merge(data, d => d3.extent(d)))
```

Because this

```
d3.extent(d3.merge(data.map(d => d3.extent(d))))
```

looks terrible for me and if you want to calculate an extent of extent of extents, this starts to look even more terrible.

**Comment by curran** [comment]
Here's a snippet I wrote to compute the extent of extents for one specific case:

https://bl.ocks.org/curran/f5282f177a5d339bc9d3e59745879fd7

```js

        yScale
          .domain([
            d3.min(stacked, function (series) {
              return d3.min(series, function (d) { return d[0]; });
            }),
            d3.max(stacked, function (series) {
              return d3.max(series, function (d) { return d[1]; });
            })
          ])
```

**Comment by mbostock** [comment]
The expectation is that you call d3.min and d3.max separately if you have nested arrays, such as:

```js
[
  d3.min(arrays, array => d3.min(array)),
  d3.max(arrays, array => d3.max(array))
]
```

We could make this a little more concise if d3.extent optionally allowed two accessors instead of just one. Then you could say:

```js
d3.extent(arrays, array => d3.min(array), array => d3.max(array))
```

**Comment by curran** [comment]
That would be cool!

Could even simplify to:

```js
d3.extent(arrays, d3.min, d3.max)
```

**Comment by mbostock** [comment]
@curran Unfortunately, no, because d3.extent passes the accessor additional arguments (the *index* and *array*), and d3.min and d3.max interpret the additional arguments as an accessor. It’s equivalent to:

```js
d3.extent(arrays, (array, i) => d3.min(array, i), (array, i) => d3.max(array, i))
```

Which results in

```
TypeError: valueof is not a function
```

https://github.com/d3/d3-array/blob/544033c59e21b12579af7344a1cecd6d56131a2a/src/min.js#L22

We could change all the functions with optional accessors to ignore accessors that aren’t functions, but that’s always felt dirty to me; I prefer to limit our overloading to checking whether an argument is null.

We could support currying instead of optional arguments. So instead of:

```js
d3.min(array, d => d.value)
```

You’d by the value accessor to d3.min using d3.min.by:

```js
d3.min.by(d => d.value)(array)
```

If you just had an array of values, it’d be the same as before:

```js
d3.min(values)
```

Now if you want to compose with d3.extent to compute the extent of an array of arrays of values, you can say:

```js
d3.extent.by(d3.min, d3.max)(arrays)
```

But this change wouldn’t be backwards-compatible.

**Comment by curran** [comment]
Aha! An interesting gotcha.

Now it's interesting to compare these two alternatives:

```js
d3.extent(arrays, array => d3.min(array), array => d3.max(array))
```

```js
d3.extent.by(d3.min, d3.max)(arrays)
```

The latter is more concise but feels more heavy in terms of API surface area (and effort required to understand this expression).

**Comment by mbostock** [comment]
Maybe I’m missing something, by why not:

```js
d3.extent(d3.merge(arrays))
```

Or, in modern browsers:

```js
d3.extent(data.flat())
```

It works for Curran’s example, too:

```js
d3.extent(d3.merge(d3.merge(stacked)))
```

Or better:

```js
d3.extent(stacked.flat(2))
```

Especially now that d3-array 2.0 takes iterables (so you could write your own flattener if desired), I don’t feel there’s a need to exposed additional auto-flattening variants of d3-array methods.
