### ISSUE TITLE
Wrong binning of histogram with default thresholds

### ISSUE THREAD

**Issue by phongvis** [d3/d3-array#66]
I use the code in https://bl.ocks.org/mbostock/3048450 with this data

`data = [10, 11, 8, 17, 2, 17, 6, 5, 3, 14, 16, 2, 1, 238, 5, 96, 5, 23, 2, 1, 17, 72, 9, 3, 63, 16, 10, 2, 10, 6, 39, 2, 1, 12, 4, 4, 9, 10, 9, 14, 8, 2, 76, 3, 15, 23, 18, 6, 6, 37, 13, 25, 25, 3, 20, 10];`

The binning is correct with the original code. But when I remove the line of specifying thresholds `.thresholds(x.ticks(20))`, the biggest element (238) isn't plotted correctly. I used the latest version of d3 v4 as exactly in the link above.

**Comment by mbostock** [comment]
That example assumes that the bins are of uniform width, which is true if the *scale*’s domain is [niced](https://github.com/d3/d3-scale/blob/master/README.md#continuous_nice) and you use [*scale*.ticks](https://github.com/d3/d3-scale/blob/master/README.md#continuous_ticks) as [*histogram*.thresholds](https://github.com/d3/d3-array/blob/master/README.md#histogram_thresholds).

If you don’t specify thresholds of uniform widths, which often happens for the first and last bin when using default thresholds, then you must change the rendering code to accommodate variable-width bins. Instead of:

```js
bar.attr("width", x(bins[0].x1) - x(bins[0].x0) - 1);
```

You’d say:

```js
bar.attr("width", d => x(d.x1) - x(d.x0) - 1));
```

I recommend looking at my newer Observable histogram example:

https://beta.observablehq.com/@mbostock/d3-histogram
