### ISSUE TITLE
Median of string values

### ISSUE THREAD

**Issue by domoritz** [d3/d3-array#70]
It would be nice if median supported string values as well.

```
> d3.median([1,2,3])
2
> d3.median(['a', 'b', 'c'])
undefined
```

Would it make sense to support this in the same method or should this be a different method since `d3.median` is designed for numbers. 

CC @jakevdp

**Comment by domoritz** [comment]
I see that this trickles down to quantile, which also does not support strings. I can see median of strings be tricky when there is no clear center as you have to decide on one. 

Maybe the cleaner way is to just ask people to write the code themselves

```js
a = ['a', 'b', 'c'];
a.sort()[Math.floor(a.length/2)]
```

**Comment by mbostock** [comment]
These methods could use a little overhaul, yes.

First, d3.median and d3.quantile should use quickselect #74 rather than the former sorting (slow) and the latter requiring sorting (tedious and/or slow). (We could maybe still provide methods for pre-sorted input as an optimization, such as d3.medianSorted and d3.quantileSorted.)

Second, we should have separate methods for ordinal versus quantitative quantiles (e.g., strings versus numbers); the former of which cannot be interpolated and so the R-7 method isn’t appropriate.

**Comment by Fil** [comment]
This issue isn't solved I'm afraid.

`d3.median(['a', 'b', 'c'])` is undefined and we provide no alternative method to find its real value.

Or do we want to promote [@domoritz 's solution](https://github.com/d3/d3-array/issues/70#issuecomment-394825654)

**Comment by mbostock** [comment]
d3.median takes numbers, so it’s expected that it’ll return undefined if you don’t pass it any numbers. It says exactly that in the README:

> Returns the median of the given iterable of numbers using the R-7 method. If the iterable contains no numbers, returns undefined. An optional accessor function may be specified, which is equivalent to calling Array.from before computing the median. This method ignores undefined and NaN values; this is useful for ignoring missing data.
